# Generated by Django 4.0.4 on 2022-04-14 16:42

import books.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_pages_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[books.validators.validate_isbn]),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_link',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
