# Generated by Django 4.0.4 on 2022-04-17 22:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 17, 22, 52, 25, 215089, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
