# Generated by Django 4.0.4 on 2022-04-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
